### ISSUE TITLE
Error when executing Dare

### ISSUE THREAD

**Issue by ufarooq** [JordanSamhi/Tools#1]
Hi @JordanSamhi ,

I am trying to use IccTA tool and using your provided Dare package. When I execute it, it cannot process APK or dex files. Here is what I am getting. 

``` 
ufaro001@ufaro001 $ ./dare/dare -d dare-out/ app-debug.apk 
Unable to open 'app-debug.apk' as zip archive
Not Zip, retrying as DEX
ERROR: unable to open 'app-debug.apk': No such file or directory
(base) ~/UCR/Research/Dare 
```
I appreciate any help, Thanks!
Umar

**Comment by JordanSamhi** [comment]
Hi @ufarooq,

First, I advise you to use this version of IC3: https://github.com/JordanSamhi/ic3,
it does need to run Dare, so it is easier.

Then, It does not seem that your issue is related to Dare directly.
Your file does not seem to be recognized as an APK, be sure it exists.
